join-message: '&7{player_name} joined the server.'
quit-message: '&7{player_name} left the server.'
death-message: '&e{player_name} died.'
kill-message: '&e{player_name} was killed by {killer_name}.'
command-only-players: '&cCommand for players only.'
setspawn-success: '&aYou set the spawn position to {x}, {y}, {z}.'
wait-to-spawn: '&6Teleporting from spawn... &7(wait 3s)'
to-spawn: '&aTeleported to spawn.'
already-in-spawn: '&cYou are already at spawn.'
kit-not-found: '&cKit {kit_name} ​​does not exist.'
already-kit: '&cYou already using kit {kit_name}.'
no-permission-kit: '&cYou do not have permission to select kit {kit_name}.'
spawn-location:
  world: world
  x: 0.5
  y: 65.5
  z: 0.5
  yaw: 0.0
  pitch: 0.0
kits-selector:
  material: CHEST
  display-name: '&aKit selector &7(right click)'
kits-inventory:
  name: 'Kit selector'
  selected-kit: '&6You have selected this kit'
  select-kit: '&eClick to select'
  you-select-kit-success: '&aYou have selected the {kit_name} kit.'
  already-selected-kit: '&cYou have already selected this kit.'
kit-description:
  knight: 'The art of the sword overcomes any challenge.'
  archer: 'A good sniper is capable of changing the entire rhythm of combat.'
  tank: 'Be strong as steel and withstand more damage.'
  healer: 'Good nutrition brings vitality.'
  grandpa: 'Throw your enemies away with your stick.'
  teleporter: 'Teleport using your pearls.' 
  enchanter: 'Your enchantments will help you overcome your opponents.'